logging:
  num_ims_per_log: 500
  num_ims_per_save_image: 100000
  num_ims_per_checkpoint: 200000
max_imsize: 128
use_full_validation: False
load_fraction_of_dataset: False
dataset: yfcc100m128
train_config:
  transition_iters: 1200000
  learning_rate: 0.00175
  amp_opt_level: O1
  batch_size_schedule:
    4: 256
    8: 256
    16: 256
    32: 128
    64: 96
    128: 64

models:
  start_channel_size: 256
  pose_size: 2
  image_channels: 3
  generator:
    running_average_decay: 0.999
  discriminator:
    structure: normal

